### PR TITLE
[16.0][MIG] base_maintenance_config: Migration to 16.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 16.0

Please @carlos-lopez-tecnativa can you review it?

@Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by carlos-lopez-tecnativa — APPROVED** [review]
LGTM, just a few comment (if possible)
To maintain consistency with Odoo's guidelines, the `Settings` Menu in all apps should be the first menu item.
Is it possible to adjust the menu sequence to place it at the top?

image
image

image

**Comment by victoralmau** [comment]
Changed to make General settings the first menu item.

**Pull request merged**
