### PR TITLE
[12.0][ADD] maintenance_equipment_custom_info

### PR DESCRIPTION
**Pull request by dalonsod**
This module extends maintenance equipments to allow having custom properties on them

### CODE REVIEW

**Comment by dalonsod** [comment]
cc @etobella @jarroyomorales @astirpe

**Review by etobella — APPROVED** [review]
LGTM

**Review by jarroyomorales — APPROVED** [review]
Tested on runbot and LGTM! The only thing I dont like is creating a new group here that is not specific for this module. If it was `group_equipment_info` or somehting like this would make more sense.

**Comment by dalonsod** [comment]
> 
> 
> Tested on runbot and LGTM! The only thing I dont like is creating a new group here that is not specific for this module. If it was `group_equipment_info` or somehting like this would make more sense.

Thanks for the feedback @jarroyomorales !!

No problem making changes on the newly created`group_maintenance_equipment`, that enables showing custom info for equiments. But, I'm not sure you're trying to say with "creating a new group here that is not specific for this module": maybe you're suggesting a simply name changing, changing the related category, or both. Is that correct?

**Comment by jarroyomorales** [comment]
Yes I didnt explain well. I meant that I didnt like to create a group named `group_maintenance_equipment` here since it is a very generic name.

**Comment by dalonsod** [comment]
> 
> 
> Yes I didnt explain well. I meant that I didnt like to create a group named `group_maintenance_equipment` here since it is a very generic name.

I agree, your suggested name looks better, I'll change it

**Comment by etobella** [comment]
@dalonsod The PR OCA/server-tools#1844 is in process of merging, can you review this PR in order to make it compatible with the new version?

**Comment by dalonsod** [comment]
> 
> 
> @dalonsod The PR [OCA/server-tools#1844](https://github.com/OCA/server-tools/pull/1844) is in process of merging, can you review this PR in order to make it compatible with the new version?

Of course I can!

**Comment by etobella** [comment]
I have stopped the merging as a change was still pending

**Comment by pedrobaeza** [comment]
Ah, OK. Please put "Request changes" in the PR for avoiding these misunderstandings.

**Comment by pedrobaeza** [comment]
Hehe, I think you didn't stop it...

**Comment by dalonsod** [comment]
Oops! Anyway as soon as possible I'll test it on v12 branch, and also applying the new view mode.

**Comment by pedrobaeza** [comment]
Is it only to put `mode="custom_info"` in the field?

**Comment by etobella** [comment]
Yes, We will create a PR today, don't worry

**Comment by dalonsod** [comment]
> 
> 
> Is it only to put `mode="custom_info"` in the field?

Actually, replacing current `context` attribute with the new `mode` one. Am I right @etobella ?

**Comment by etobella** [comment]
exactly

**Pull request merged**
