### PR TITLE
[16.0][MIG] maintenance_project

### PR DESCRIPTION
**Pull request by dalonsod**
Standard migration

### CODE REVIEW

**Comment by dalonsod** [comment]
@victoralmau could you review? Thanks!

**Review by victoralmau — APPROVED** [review]
Code review OK

**Comment by dalonsod** [comment]
@sanchonuria could you review? Thanks!

**Comment by dalonsod** [comment]
@mmrondon could you review? Thanks!

**Review by sanchonuria — APPROVED** [review]
LGTM @etobella

**Pull request merged**
