### PR TITLE
[ADD] maintenance_team_hierarchy

### PR DESCRIPTION
**Pull request by etobella**
This module allows to define a hierarchy of teams.
Also, requests of a team will be computed as direct requests of team and requests of childs.

@jarroyomorales @jbeficent @lreficent

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Tested on runbot + code review. LGTM :+1:

**Review by jarroyomorales — COMMENTED** [review]
LGTM but I have some doubts regarding the assignation of members to teams. I think members should only be assigned to teams without childs (leaf nodes) and other teams should compute its members by collecting the members of its child.

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@jarroyomorales To me this could quickly become complex to manage. To me it's best if the users manage it manually.

**Comment by jarroyomorales** [comment]
@jbeficent Did the bot get stuck?

**Comment by jarroyomorales** [comment]
Reran Travis and it worked :smile:

**Pull request merged**
