### PR TITLE
[11.0][REF] convert get_relativedelta function to MaintenancePlan class method

### PR DESCRIPTION
**Pull request by mymage**
As pointed out in #182, for me is better to have get_relativedelta as a MaintenancePlan method to allow hineritance.

PS. Proposed for v11.0 because I'm working here, but in case of success I will port it to nex versions.

### CODE REVIEW

**Review by etobella — APPROVED** [review]

**Review by marcelofrare — APPROVED** [review]
LGTM 
Thanks @mymage!

**Comment by mymage** [comment]
@etobella I saw the error. If you don't have time before, this eveninig I will try to understand and fix it.

**Comment by etobella** [comment]
It is not really an error. Something happened with travis, probably a timeout. let's try it again :wink: 
/ocabot merge minor

**Comment by mymage** [comment]
@etobella after the merge in this version, do you think that I can do PR for all the other versions in "parallel" or wait a version a time?

**Comment by etobella** [comment]
All versions is fine for me

**Comment by mymage** [comment]
@etobella aaaargh: I pushed for mistake, hope there isn't a problem.

**Comment by etobella** [comment]
/ocabot merge minor
Let's try again....

**Pull request merged**
