### PR TITLE
[14.0][MIG] maintenance_timesheet_time_control: Migration to 14.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 14.0

Locked by:
- [x] `maintenance_timesheet`: https://github.com/OCA/maintenance/pull/271

Please @pedrobaeza and @ernestotejeda can you review it?

@Tecnativa TT40942

### CODE REVIEW

**Comment by chienandalu** [comment]
You can rebase it

**Comment by victoralmau** [comment]
Rebase done.

**Review by pedrobaeza — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
Tested :+1:

**Pull request merged**
