### PR TITLE
[16.0][MIG] maintenance_equipment_image: Migration to 16.0

### PR DESCRIPTION
**Pull request by FrancoMaxime**
Here is the migration of maintenance_equipment_image from the pull request of @mymage 

see https://github.com/OCA/maintenance/pull/257

### CODE REVIEW

**Review by baimont — APPROVED** [review]

**Review by AnizR — APPROVED** [review]
Code LGTM

**Review by rousseldenis — APPROVED** [review]
Code and functional review

**Review by sbejaoui — APPROVED** [review]

**Review by apineux — APPROVED** [review]

**Review by mamcode — APPROVED** [review]
Thanks

**Review by etobella — APPROVED** [review]

**Pull request merged**
