### PR TITLE
[17.0][MIG] base_maintenance

### PR DESCRIPTION
**Pull request by Anxo82**
Standard migration

### CODE REVIEW

**Comment by dalonsod** [comment]
@Anxo82 clean commit history is pending, could you check? https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

**Comment by Anxo82** [comment]
Hi @FernandoRomera @flotho, could you review? Thanks!

**Review by peluko00 — APPROVED** [review]
LGTM, tested in runboat

**Comment by Anxo82** [comment]
Hi @marcelsavegnago  @Christian-RB , could you review? Thanks!

**Review by FernandoRomera — APPROVED** [review]
LGTM

**Review by AntoniRomera — APPROVED** [review]
LGTM

**Comment by FernandoRomera** [comment]
@etobella is this PR ready to be merged? Thanks!

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
