### PR TITLE
[12.0][REF] convert get_relativedelta function to MaintenancePlan class method

### PR DESCRIPTION
**Pull request by mymage**
Follow up of #183
Moving get_relativedelta function to MaintenancePlan method

### CODE REVIEW

**Comment by mymage** [comment]
@etobella @marcelofrare I did some little changes to try to get the codecov/project green without success.

**Comment by etobella** [comment]
Can you return to 33b59fe9ee2d404471037efd090c2cc93c8a72ea in order to avoid the extra changes? The codecov/product disminution is due to less lines to evaluate. You patch has a 100% diff hit, so it is fine.
just do:
```
git reset 33b59fe9ee2d404471037efd090c2cc93c8a72ea --hard
git push -f
```

**Comment by mymage** [comment]
@etobella I followed your suggestion but I think without success. What do you think if we close this PR and open a new one?

**Review by etobella — APPROVED** [review]
Don't worry, this one is fine :wink:

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
