### PR TITLE
[12.0][FIX] maintenance_plan: fix new request date

### PR DESCRIPTION
**Pull request by mariadforgeflow**
Fix new request date when plan start date is later.

### CODE REVIEW

**Review by etobella — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
Forward port of https://github.com/OCA/maintenance/pull/202.

**Comment by LoisRForgeFlow** [comment]
@mariadforgeflow Could you check travis?

**Comment by mariadforgeflow** [comment]
@LoisRForgeFlow fixed:)

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
