### PR TITLE
[13.0][FIX] maintenance_plan: homogenize versions

### PR DESCRIPTION
**Pull request by mariadforgeflow**
Apply same logic as in v11 (#202)

### CODE REVIEW

**Review by etobella — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Comment by mariadforgeflow** [comment]
Hi@etobella! Could you merge this and https://github.com/OCA/maintenance/pull/213 please? Thanks!!

**Comment by mariadforgeflow** [comment]
@etobella  I haven't changed anything in the test that fails. It is failing because there is a test with a monthly plan that starts in today_date and next month is February that has 28 days. This doesn't fail usually and it is set like that in all versions. I don't know if you prefer to wait till tomorrow that won't fail.

**Comment by mariadforgeflow** [comment]
@etobella hi! could you try to merge this again? Thanks:)

**Pull request merged**
