### PR TITLE
[14.0] [MIG] maintenance_request_stage_transition

### PR DESCRIPTION
**Pull request by mariadforgeflow**
Standard migration to v14

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@mariadforgeflow you can add etobella as mantainer

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by ChristianSantamaria — APPROVED** [review]
LGTM 👍

**Review by etobella — APPROVED** [review]
LGTM

**Pull request merged**
