### PR TITLE
[12.0][FIX]maintenance_plan. Migration scripts.

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Migration scripts are failing now.

@ForgeFlow

### CODE REVIEW

**Review by etobella — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Working in real database migration.

**Review by MiquelRForgeFlow — CHANGES_REQUESTED** [review]
change the number of the folder to 11.0.2.3.0

**Comment by AaronHForgeFlow** [comment]
> change the number of the folder to 11.0.2.3.0

Do you mean 12.0.2.3.0? Would that affect databases in v12?

**Comment by dreispt** [comment]
AFAICT that directory name change won't make a difference.

**Review by dreispt — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Folder renamed to 12.0.2.3.0

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
