### PR TITLE
[11.0][IMP] maintenance_plan_activity: Remove filtereds, simplify search

### PR DESCRIPTION
**Pull request by etobella**
This PR reuses the changes from #59 in order to simplify the code
@NuriaMForgeFlow

### CODE REVIEW

**Comment by etobella** [comment]
@jarroyomorales

**Review by jarroyomorales — APPROVED** [review]
I guess this is why you did #59

**Comment by etobella** [comment]
Yes, I think it was good to improve the code here :smile:

**Comment by etobella** [comment]
@AdriaGForgeFlow You are the creator of the module. Can you check?

**Review by AdriaGForgeFlow — APPROVED** [review]
Looks good :+1:

**Pull request merged**
