### PR TITLE
[12.0][IMP] maintenance_project: add report support for requests

### PR DESCRIPTION
**Pull request by dalonsod**
This improvement adds project and task data to the new maintenance request report provided by #94

### CODE REVIEW

**Comment by dalonsod** [comment]
cc @jarroyomorales @marcelsavegnago

**Review by marcelsavegnago — APPROVED** [review]
it´s ok for me.

**Review by jarroyomorales — APPROVED** [review]
LGTM too :+1:

**Review by etobella — APPROVED** [review]

**Pull request merged**
