### PR TITLE
[13.0][MIG] maintenance_stock

### PR DESCRIPTION
**Pull request by rhe-mastercore**
Standard migration to v13.
@dalonsod

### CODE REVIEW

**Comment by dalonsod** [comment]
@rhe-mastercore I don't know why the PR doesn't pass runbot, but you should follow the complete guide https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0 , starting with the processes for commit history preservation and pre-commit stuff, otherwise the PR will not be accepted :(

**Comment by pedrobaeza** [comment]
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0.

**Comment by etobella** [comment]
@rhe-mastercore You are not maintaining commit history, follow the guide as @dalonsod suggests please

**Comment by rhe-mastercore** [comment]
@etobella could you explain the problem to me?
I followed the guide, and I don't see my problem, sorry

**Comment by dalonsod** [comment]
@rhe-mastercore in this section of the guide https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch there are several git commands you shoud execute prior to make the code revision itself (the code lines before "Adapt the module to the 13.0 version following tasks to do"). With these lines executed, commit history is maintained and code properly formatted. Once these tasks are finished, you can adapt the code with 13.0 required modifications you detect.

**Comment by dalonsod** [comment]
@rhe-mastercore would you resume this PR?

**Comment by rhe-mastercore** [comment]
yes of course, I already understood what I should do in the next few hours I will make the correction.

**Comment by dalonsod** [comment]
hello @rhe-mastercore any news on this?

**Pull request closed without merging**
