### PR TITLE
14.0 [MIG] maintenance_equipment_sequence

### PR DESCRIPTION
**Pull request by mariadforgeflow**
Standard migration to v14
@MiquelRForgeFlow @GenisPForgeFlow

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@mariadforgeflow I think you did something wrong in your pre-commit commit, and then the migration commit is also wrong. Please, could you redo them again?

Also you may add @AdriaGForgeFlow as maintaner hehe

**Comment by mariadforgeflow** [comment]
@MiquelRForgeFlow I've done the pre-commit and the commit again, I hope there's nothing wrong now. I also added @AdriaGForgeFlow as maintainer :)

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by dalonsod — APPROVED** [review]
Tested on runbot, LGTM.

Not blocking, but maybe it's a good time for some improvements, like:
- Adding some demo data.
- Split python and xml files, one for each model.

**Comment by dalonsod** [comment]
Not blocking too, adding some of the new maintenance category fields to `search` and `tree` view should be a good point.

**Review by flotho — APPROVED** [review]
LGTM

**Review by etobella — APPROVED** [review]
LGTM

**Pull request merged**
