### PR TITLE
[13.0][IMP] maintenance_plan: Skip assigned mail + Activity mail of the requests created from plans

### PR DESCRIPTION
**Pull request by victoralmau**
Skip assigned mail + Activity mail of the requests created from plans

Please  @pedrobaeza and @CarlosRoca13 can you review it?

@Tecnativa TT41870

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@dalonsod what do you think about this change for avoid hammering people with a lot of assignation mails?

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by dalonsod** [comment]
This improvement looks good... is it possible to be this new behavior parametrized for each plan (and set as "do not notify to follower when creating requests" as default)? Then, current functionality could be still achieved if needed

**Comment by victoralmau** [comment]
Changes done (new field created in plan to be able to configure it).

**Comment by dalonsod** [comment]
Not blocking,

- New parameter is set to `False` as default. Maybe it could be set to `True` (suggested behavior, the original one for this improvement you looked for), so be repeatedly notified should be strictly chosen.
- `po` files, should be excluded from commit?

**Comment by victoralmau** [comment]
> Not blocking,
> 
>     * New parameter is set to `False` as default. Maybe it could be set to `True` (suggested behavior, the original one for this improvement you looked for), so be repeatedly notified should be strictly chosen.
Changed to True by default.
>     * `po` files, should be excluded from commit?
I think it is correct, the translation is already added directly without the need to do it in weblate.

**Comment by pedrobaeza** [comment]
About changing PO files, there may be the possibility of a conflict because meanwhile, there's a change in Weblate, or not all changes are pushed back from Weblate to GitHub, but as the translation coverage is good, the chances are very low, and this pull request life is short.

**Pull request merged**
