### PR TITLE
[17.0][MIG] maintenance_account: Migration to version 17.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
- Standard migration to v17

@Tecnativa
TT50086
@pedrobaeza @victoralmau

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]
Code review OK

**Comment by carolinafernandez-tecnativa** [comment]
ping @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
