### PR TITLE
[16.0][MIG] maintenance_equipment_sequence: Migration to 16.0

### PR DESCRIPTION
**Pull request by kaynnan**
cc @marcelsavegnago 

#240

### CODE REVIEW

**Comment by kaynnan** [comment]
ping @AdriaGForgeFlow

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by christian-ramos-tecnativa — APPROVED** [review]
LGTM

**Review by etobella — CHANGES_REQUESTED** [review]
Migration folder should be removed...

**Comment by kaynnan** [comment]
> Migration folder should be removed...

@etobella Thanks for the comment, i made the adjustments

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
