### PR TITLE
[12.0][UPD] Add addons table and translate status on README.rst

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
@jarroyomorales Are you do review this PR please?

**Comment by jarroyomorales** [comment]
@marcelsavegnago LGTM! but how will this be maintained? Should it be updated in the PR where a version changes or a module is added?

**Review by etobella — CHANGES_REQUESTED** [review]
It is interesting, but it should be maintained automatically by gitbot, so I think the script of the gitbot needs to be upgraded

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago LGTM! but how will this be maintained? Should it be updated in the PR where a version changes or a module is added?

@jarroyomorales At first I imagined that the maintenance would be done via PR.

**Comment by marcelsavegnago** [comment]
> It is interesting, but it should be maintained automatically by gitbot, so I think the script of the gitbot needs to be upgraded

@etobella  In this case, I don't know the scope of action of gitbot .. but I will research.

**Comment by marcelsavegnago** [comment]
> > It is interesting, but it should be maintained automatically by gitbot, so I think the script of the gitbot needs to be upgraded
> 
> @etobella In this case, I don't know the scope of action of gitbot .. but I will research.

@etobella I researched the oca-github-bot and made the correction in README.rst so that it is updated by the bot. What do you think ?

https://github.com/OCA/oca-github-bot/tree/8b38c269ca1ebd73e8920fabec4d863fd8e651a7#on-push-to-main-branches

https://github.com/OCA/oca-github-bot/blob/8b38c269ca1ebd73e8920fabec4d863fd8e651a7/src/oca_github_bot/tasks/main_branch_bot.py#L21

cc @jarroyomorales

**Review by jarroyomorales — APPROVED** [review]

**Review by etobella — APPROVED** [review]
Thanks!!!

Great to know this :wink:

**Pull request merged**
