### PR TITLE
[11.0][MIG] base_maintenance_config (split in 2 separate modules)

### PR DESCRIPTION
**Pull request by astirpe**
While porting `base_maintenance_config` to V11,  I'm splitting it in two different modules:

- `base_maintenance_config`, containing only the general configuration view;
- `base_maintenance_group`, containing all the stuff related the newly added groups.

### CODE REVIEW

**Review by dalonsod — APPROVED** [review]
LGTM 👍

**Comment by dalonsod** [comment]
@pedrobaeza one month before my approval, this PR wasn't automatically marked as approved. Is there any missing configuration in this repo, or is this the expected behavior?

**Comment by pedrobaeza** [comment]
It requires 2 approvals.

**Comment by dalonsod** [comment]
Thanks, @pedrobaeza

**Review by jarroyomorales — APPROVED** [review]
Code review looks great to me!

**Pull request merged**
