### PR TITLE
[15.0][FIX] maintenance_equipment_sequence: Add Readme migrations folder

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**
Add Readme because pre-commit of other modules are failing.

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]

**Comment by etobella** [comment]
I don't get the need of this, pre-commit is working properly on 15.0 :thinking:

**Comment by mariadforgeflow** [comment]
Hi @etobella it was failing in #196. 
image
Do you have any other suggestion on how to fix this? Thank you!!

**Comment by etobella** [comment]
That's weird.. Have you done pre-commit -a on your system? It happened to me sometimes, but after the second pre-commit the error was never raised again :thinking:

**Comment by mariadforgeflow** [comment]
Yes.. more than once and it was still failing. I've just retried it in my local and I am getting the same error:(

**Comment by etobella** [comment]
/ocabot merge patch
I will add it as it has no problems, but it is weird :thinking:

**Pull request merged**
