### PR TITLE
[FIX] base_maintenance: Add button as first element on sheet

### PR DESCRIPTION
**Pull request by etobella**

### CODE REVIEW

**Review by albariera — APPROVED** [review]

**Comment by etobella** [comment]
Current behavior
image

Expected:
image

**Review by olgamarcocb — APPROVED** [review]
:+1:

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Comment by etobella** [comment]
/ocabot merge patch

Fast tracking as it is just a view error but it is showing incorrectly

**Pull request merged**
