### PR TITLE
[15.0][MIG] maintenance_timesheet: Migration to 15.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 15.0

Locked by:
- [x] `base_maintenance`: https://github.com/OCA/maintenance/pull/275
- [x] `maintenance_project`: https://github.com/OCA/maintenance/pull/259

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT41113

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Can you add the temporal dependencies so it can be tested?: https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference(s)-to-another-pull-request(s)

**Comment by victoralmau** [comment]
> Can you add the temporal dependencies so it can be tested?: https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference(s)-to-another-pull-request(s)

Thanks, but in this case I can't do it because the related PR needs changes to be installed.

**Comment by victoralmau** [comment]
Rebase done, now it's ready to review.

**Review by pedrobaeza — APPROVED** [review]

**Comment by victoralmau** [comment]
Ping @chienandalu

**Review by chienandalu — APPROVED** [review]
Tested :+1:

**Pull request merged**
