### PR TITLE
[15.0][MIG] base_maintenance

### PR DESCRIPTION
**Pull request by mariadforgeflow**
Standard migration to v15.
@ForgeFlow

### CODE REVIEW

**Comment by etobella** [comment]
Can you squash administrative commits??? Following the migration guide:

Squash administrative commits (if any) with the previous commit for reducing commit noise. They are named as "[UPD] README.rst", "[UPD] Update $MODULE.pot", "Update translation files" and similar names, and comes from OCA-git-bot, oca-travis or oca-transbot. IMPORTANT: Don't squash legit translation commits, authored by their translators, with the message "Translated using Weblate (...)".

**Comment by mariadforgeflow** [comment]
@etobella Done!

**Comment by OriolVForgeFlow** [comment]
LGTM! Minor coment: Update the readme because the "Creates the unexisting search view for maintenance team." is already on Odoo Standard :-)

**Review by OriolVForgeFlow — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Pull request merged**
