### PR TITLE
[14.0][IMP] maintenandce_equipment_image: Add zoom

### PR DESCRIPTION
**Pull request by sanchonuria**

### CODE REVIEW

**Comment by sanchonuria** [comment]
Added zoom to the image when hovering the mouse over it.

Captura desde 2023-04-17 15-32-32

**Review by etobella — APPROVED** [review]

**Review by kluna1998 — APPROVED** [review]
LGTM! 👍🏽

**Comment by dalonsod** [comment]
@sanchonuria please fix typo in commit message. Thanks for the contribution!

**Comment by sanchonuria** [comment]
@dalonsod Done, thanks for the review!

**Comment by dalonsod** [comment]
PR hasn't been updated, so commit message is still wrong

**Review by dalonsod — APPROVED** [review]

**Review by kluna1998 — APPROVED** [review]

**Review by etobella — APPROVED** [review]
LGTM
/ocabot merge patch

**Pull request merged**
