### PR TITLE
[IMP] maintenance_equipment_tags: add tags to equipment requests

### PR DESCRIPTION
**Pull request by cubells**
Improving module by adding tags to maintenance requests.
Tags are propagated from equipment to request.

### CODE REVIEW

**Review by rlizana — APPROVED** [review]
:+1:  LGTM

**Review by etobella — COMMENTED** [review]
I don't really like the change, as you are using the same tags for equipments and requests and it has no sense in my opinion... I would prefer to have a different set of tags with no relation IMO

**Comment by cubells** [comment]
@etobella thanks for the revision.

Now, they have different tags as you requested.

**Comment by cubells** [comment]
@etobella Travis error is not related to module.

**Pull request closed without merging**
