### PR TITLE
[13.0][IMP] maintenance_project: add report support for requests

### PR DESCRIPTION
**Pull request by dalonsod**
Forward-port of #96

### CODE REVIEW

**Comment by dalonsod** [comment]
cc @marcelsavegnago @etobella 
I'll forward port it to v14 too.

**Review by jarroyomorales — APPROVED** [review]

**Review by lmiguens-solvos — APPROVED** [review]
LGTM

**Comment by dalonsod** [comment]
@etobella could you merge this PR? Thanks!

**Review by etobella — APPROVED** [review]

**Pull request merged**
