### PR TITLE
[11.0][FIX] maintenance_plan: fix new request date 

### PR DESCRIPTION
**Pull request by mariadforgeflow**
- Fix new request date when plan start date is later.
- Make Request Date visible in tree view.

@LoisRForgeFlow

### CODE REVIEW

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by etobella — APPROVED** [review]
LGTM Check travis please

**Comment by mariadforgeflow** [comment]
@etobella fixed!

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
