### PR TITLE
[14.0][IMP] maintenance_plan: add chatter

### PR DESCRIPTION
**Pull request by mariadforgeflow**

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
I don't see why not

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
@mariadforgeflow will you forward port this?

**Comment by mariadforgeflow** [comment]
@MiquelRForgeFlow Yes! Done in https://github.com/OCA/maintenance/pull/236

**Pull request merged**
