### PR TITLE
[12.0] [MIG] maintenance_equipment_sequence

### PR DESCRIPTION
**Pull request by NuriaXifre**
Migration of the module maintenance_equipment_sequence to v12

### CODE REVIEW

**Review by etobella — APPROVED** [review]
No major changes, LGTM :+1:

**Review by jarroyomorales — APPROVED** [review]
LGTM too :+1:

**Comment by LoisRForgeFlow** [comment]
@NuriaMForgeFlow  Can you include https://github.com/OCA/maintenance/pull/54 here?

**Comment by etobella** [comment]
@LoisRForgeFlow comments have been attended, I know the CLA has been signed (change of name, I know :stuck_out_tongue_closed_eyes: ), has it been fixed?

**Comment by AdriaGForgeFlow** [comment]
We could use this PR to change all Eficent references to ForgeFlow @NuriaMForgeFlow

**Review by AdriaGForgeFlow — APPROVED** [review]
Code and functional review :+1:

**Review by LoisRForgeFlow — APPROVED** [review]
@etobella yes, this is good now!

thanks @NuriaMForgeFlow

**Pull request merged**
