### PR TITLE
[13.0][IMP] maintenance_timesheet: add report support for requests

### PR DESCRIPTION
**Pull request by dalonsod**
Forward-port of #101

### CODE REVIEW

**Comment by dalonsod** [comment]
cc @etobella @jarroyomorales 
After this PR I'd migrate `maintenance_timesheet` to v14

**Review by jarroyomorales — APPROVED** [review]
Tested on runbot and LGTM :+1:

**Review by lmiguens-solvos — APPROVED** [review]
LGTM

**Pull request merged**
