### PR TITLE
[13.0][MIG] maintenance_equipment_scrap

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by dalonsod — CHANGES_REQUESTED** [review]
Code and functional review.
I specially tested changes on `equipment_scrap_template_id` computed and editable field, works as expected 👍 

Only one thing: according to migration rules to v13, is it possible to squash certain administrative commits for v12 implementation?

**Comment by etobella** [comment]
@astirpe It works as expected, but I have a few questions.
* Why do you need to edit the scrap template from the equipment?
* Could you edit the default template in order to not write Serial Number False if it is undefined?

**Comment by astirpe** [comment]
> is it possible to squash certain administrative commits for v12 implementation?

@dalonsod all administrative commits for V12 have different authors


> Why do you need to edit the scrap template from the equipment?

@etobella for flexibility of use. I was made that way since the beginning.

**Comment by etobella** [comment]
Thanks!!! If you merge the migration commits we can proceed with merge

**Comment by astirpe** [comment]
Done!

**Review by etobella — APPROVED** [review]

**Pull request merged**
