### PR TITLE
[11.0][FIX] maintenance_plan_activity: avoid error in indeterministic test

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Selection_052

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
@ForgeFlow 
@etobella

**Comment by MiquelRForgeFlow** [comment]
I don't know if I should forward port it.

**Comment by etobella** [comment]
This has no sense for me, you are saying that it can be between 2 and 4??? Something different might be happening, but your solution has no sense without some more explanation

**Comment by etobella** [comment]
Executing again the tests are working correctly, IMO this has no sense and the problem came from another site, so I close PR

**Pull request closed without merging**
