### PR TITLE
[FIX] maintenance_equipment_scrap: Scrap date is hidden

### PR DESCRIPTION
**Pull request by etobella**

### CODE REVIEW

**Review by mamcode — APPROVED** [review]
Looks good and I agree with the change. 

I only have the doubt why Odoo makes the scrapping date only visible in developer mode by default...

**Comment by etobella** [comment]
It is something they never changed from the origin

https://github.com/odoo/odoo/commit/f63d2d5135c0a6e3d032082ec8bfce16c40add69

**Review by dalonsod — APPROVED** [review]
:+1:

**Pull request merged**
