### PR TITLE
[11.0][ADD] base_maintenance

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
~Adds active field to maintenance team.~ 

EDIT:

This module extends the functionality of Odoo Maintenance module to add
some basic features that are standard in other Odoo apps:

* Administrator is added to the equipment managers by default.
* Active field in maintenance team.
* Team leader in maintenance team.
* Description field in maintenance team.
* Creates the unexisting search view for maintenance team.
* Empty button box on maintenance request to be extended by other modules.

@Eficent

### CODE REVIEW

**Review by jarroyomorales — APPROVED** [review]
LGTM! :+1:

**Comment by dreispt** [comment]
I'm not fond of one field modules.
Can't we throw this in an existing basic module, such as `base_maintenance_config`?

**Comment by LoisRForgeFlow** [comment]
@dreispt In our particular case we are not using base_maintenance_config, and I don't see it being dependency of any other module in OCA/maintenance, but I'm open to include this there.

Any extra opinion here? @astirpe @espo-tony @jbeficent

**Review by etobella — APPROVED** [review]

**Review by astirpe — APPROVED** [review]
For me this module is okay.
There exist in OCA other modules for archiving documents, working the same way as this module. I don't see any valid reason to reject this one.

**Comment by dreispt** [comment]
Not blocking anything, just suggesting a different approach.
Feel free to proceed with this if other maintainers agree.

**Comment by LoisRForgeFlow** [comment]
I'm thinking that this module can be a maintenance team extension, I will also add here a couple of more fields: team leader and description. So, which would be a good name? maintenance_team_detail? maintenance_team_extension?

**Comment by astirpe** [comment]
`maintenance_team` ?

**Comment by etobella** [comment]
`maintenance_team` seems good for me.

**Comment by jarroyomorales** [comment]
I would go for `maintenance_team_ + something` since just `maintenance_team` doesnt say much.
`maintenance_team_info` or `maintenance_team_extension` for example

**Comment by LoisRForgeFlow** [comment]
Following the discussion at https://github.com/OCA/maintenance/issues/42, I have renamed the module to base_maintenance. The purpose is to use it to consolidate all small generic small tweaks to maintenance app that are quite standard in other Odoo apps.

**Comment by LoisRForgeFlow** [comment]
@jarroyomorales I added the button box, could you please check if this works for you?

Screenshot from 2019-11-20 12-17-58
(the archive button on the screenshot is not added is just to show how it will look)

**Comment by jarroyomorales** [comment]
Perfect. Thank you!

**Review by etobella — APPROVED** [review]
LGTM :+1:

**Review by jarroyomorales — APPROVED** [review]

**Comment by astirpe** [comment]
I'm noticing that not any group has rights to create,modify or delete teams.
It' missing a rule like this:

`access_maintenance_team_admin_user,maintenance.team.admin.user,model_maintenance_team,group_equipment_manager,1,1,1,1`

@lreficent could you check?

**Comment by LoisRForgeFlow** [comment]
@astirpe thanks for noticing. I saw that the security fixes done in this module are out-of-the-box in v12 so I also added a small note in the README.

**Review by astirpe — APPROVED** [review]

**Pull request merged**
