### PR TITLE
[13.0][MIG] maintenance_equipment_tags

### PR DESCRIPTION
**Pull request by jarroyomorales**
Standard migration to v13.

@etobella @dalonsod @marcelsavegnago

### CODE REVIEW

**Comment by dalonsod** [comment]
@jarroyomorales one question, is `setup.py` required in this addon?

**Review by etobella — APPROVED** [review]
Not really, but will be automatically generated by ocabot, so no harm from my side.

**Review by dalonsod — COMMENTED** [review]
:+1:

**Review by dalonsod — APPROVED** [review]

**Pull request merged**
