### PR TITLE
[14.0][IMP] maintenance_plan: Change tests to allow inheritance

### PR DESCRIPTION
**Pull request by victoralmau**
FWP from 13.0: https://github.com/OCA/maintenance/pull/306

Change tests to allow inheritance

Please @pedrobaeza and @CarlosRoca13 can you review it?

@Tecnativa TT41735

### CODE REVIEW

**Comment by pedrobaeza** [comment]
For reducing the diff, just do both classes in the same file.

**Comment by victoralmau** [comment]
Ok, changes done.

**Comment by pedrobaeza** [comment]
Oh, I didn't see that you were also changing TransactionCase to SavepointCase. In that case, the diff is similar, so you can revert. Sorry for the noise.

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
