### PR TITLE
[14.0] [IMP] maintenance_equipment_status: Make status name translatable

### PR DESCRIPTION
**Pull request by HekkiMelody**
Simple change to make the status' name translatable

### CODE REVIEW

**Comment by HekkiMelody** [comment]
No idea about the pre-commit failure tbh.

**Review by kluna1998 — APPROVED** [review]

**Review by etobella — APPROVED** [review]
Makes sense to me

/ocabot merge minor

**Comment by HekkiMelody** [comment]
Pre-commit doesn't work (anymore?) because the Flake8 project doesn't exist on gitlab anymore
https://gitlab.com/pycqa

https://github.com/OCA/maintenance/blob/ec076db5e805c8b5c13f4d46869f69612b8645fb/.pre-commit-config.yaml#L116-L121

Issue has been fixed upstream by OCA's maintainer tools @etobella https://github.com/OCA/maintainer-tools/commit/a24deac77aff2f3c968b3b4c269d6aec91a379da

**Comment by etobella** [comment]
Problem with the flake8 github. Should be fixed now.
/ocabot merge minor

**Pull request merged**
