### PR TITLE
[14.0][IMP] maintenance_plan: improved embedded tree view labels

### PR DESCRIPTION
**Pull request by pedrocs-exo**
This PR addresses the problems reported on #206

### CODE REVIEW

**Review by etobella — APPROVED** [review]
Your fixes proably work on your screen, but the same error might happen with a smaller screen :cry: However, I am approving it as it has sense to make titles smaller.

Have you tryied to install web_responsive and see what happens?

**Comment by pedrocs-exo** [comment]
Hi @etobella 
I usually use muk_web_theme. With web_responsive, the sheet's right termination is clean as you can see on the picture:
imagem

But as you said, it still makes sense to shorten the labels. IMHO a few columns could be removed from the tree view and displayed on the form view only.

**Comment by etobella** [comment]
Sure! Can you make a proposal?

**Review by dreispt — APPROVED** [review]

**Pull request merged**
