### PR TITLE
[12.0] [ADD] maintenance_project_plan

### PR DESCRIPTION
**Pull request by dalonsod**
This module adds project and task fields to a Maintenance Plan, which will be automatically propagated to any maintenance request generated from a Plan

### CODE REVIEW

**Comment by astirpe** [comment]
Test fails:


```
2019-09-30 23:21:18,493 5627 ERROR openerp_test odoo.addons.maintenance_plan.tests.test_maintenance_plan: FAIL: test_next_maintenance_date (odoo.addons.maintenance_plan.tests.test_maintenance_plan.TestMaintenancePlan)

2019-09-30 23:21:18,493 5627 ERROR openerp_test odoo.addons.maintenance_plan.tests.test_maintenance_plan: Traceback (most recent call last):

2019-09-30 23:21:18,493 5627 ERROR openerp_test odoo.addons.maintenance_plan.tests.test_maintenance_plan: `   File "/home/travis/build/OCA/maintenance/maintenance_plan/tests/test_maintenance_plan.py", line 35, in test_next_maintenance_date

2019-09-30 23:21:18,494 5627 ERROR openerp_test odoo.addons.maintenance_plan.tests.test_maintenance_plan: `     today + timedelta(days=plan.period))

2019-09-30 23:21:18,494 5627 ERROR openerp_test odoo.addons.maintenance_plan.tests.test_maintenance_plan: ` AssertionError: datetime.date(2019, 10, 31) != datetime.date(2019, 10, 30)
```

**Comment by dalonsod** [comment]
I see, but the failed test belongs to `maintenance_plan`. As far as I know, the new module doesn't change request dates calculation, it only adds some plan demo data.

I'll test locally and debug it anyway.

**Comment by dalonsod** [comment]
@astirpe I don't know why, but the test is now OK, I didn't actually change anything. Maybe the test was affected by travis runtime (near midnight)

**Review by astirpe — APPROVED** [review]
Code review OK. I didn't test it.

**Comment by lromero-solvos** [comment]
Tested on runbot. Only one issue: in a plan, you can fill the task without project, and should be forbidden.

**Comment by dalonsod** [comment]
@lromero-solvos well, I think the issue is solved (`onchange `method implemented for `project_id`).

Otherwise, travis failed because of project_timesheet issue, #32 is arriving...

**Review by lromero-solvos — APPROVED** [review]
LGTM 👍

**Pull request merged**
