### PR TITLE
[17.0][MIG] maintenance_equipment_hierarchy

### PR DESCRIPTION
**Pull request by dalonsod**
Standard migration + search view improvement

### CODE REVIEW

**Comment by dalonsod** [comment]
@FrancoMaxime @IT-Ideas could you review? Thanks!

**Review by dreispt — APPROVED** [review]

**Review by FrancoMaxime — APPROVED** [review]
LGTM: code review

Hi @dalonsod,
Thanks for your pull request and thanks a lot for asking my review.

Have a good day,
Maxime

**Comment by dalonsod** [comment]
@etobella is this PR ready to be merged? Thanks!

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
