### PR TITLE
[16.0][MIG] base_maintenance: Migration to 16.0

### PR DESCRIPTION
**Pull request by FernandoRomera**

### CODE REVIEW

**Comment by FernandoRomera** [comment]
#240

**Review by flotho — APPROVED** [review]
tested on runboat, LGTM

**Review by AntoniRomera — APPROVED** [review]

**Review by MRomeera — APPROVED** [review]
Ok

**Comment by pedrobaeza** [comment]
Can you please add 34fb82ceee178f357f44b2a0105e5563bb6c7fa4 that is being added in lower branches?

**Comment by FernandoRomera** [comment]
@pedrobaeza 
Done.

**Review by pedrobaeza — COMMENTED** [review]
Next time, please cherry-pick the commit instead for preserving the attribution.

/ocabot migration base_maintenance
/ocabot merge nobump

**Pull request merged**
