### PR TITLE
[13.0][MIG] maintenance_project_plan

### PR DESCRIPTION
**Pull request by dalonsod**
Standard migration with minor changes on tests

### CODE REVIEW

**Review by etobella — APPROVED** [review]
LGTM

**Comment by dalonsod** [comment]
When #81 is approved, I'll add those changes to this PR

**Comment by dalonsod** [comment]
> 
> 
> When #81 is approved, I'll add those changes to this PR

Done!

**Review by lmiguens-solvos — APPROVED** [review]
LGTM 👍

**Pull request merged**
