### PR TITLE
[13.0][MIG] maintenance_equipment_hierarchy

### PR DESCRIPTION
**Pull request by dalonsod**
Known issues:

- ~~built-in Odoo recursion checking runs before `_check_equipment_recursion` equipment method, and this one is never executed~~.

### CODE REVIEW

**Comment by dalonsod** [comment]
cc @AdriaGForgeFlow

**Review by jarroyomorales — COMMENTED** [review]
Tested on runbot and works as expected. Regarding the recursion check I think we can remove that function. At first I thought about overriding the function that checks this to change the message but I think its not worth it.
https://github.com/odoo/odoo/blob/13.0/odoo/models.py#L3961

**Comment by dalonsod** [comment]
> 
> 
> Tested on runbot and works as expected. Regarding the recursion check I think we can remove that function. At first I thought about overriding the function that checks this to change the message but I think its not worth it.
> https://github.com/odoo/odoo/blob/13.0/odoo/models.py#L3961

Removed recursion checks

**Review by etobella — APPROVED** [review]
LGTM :+1:

**Review by JoanSForgeFlow — APPROVED** [review]

**Pull request merged**
