### PR TITLE
[11.0][IMP] set track_visibility on parent_id

### PR DESCRIPTION
**Pull request by etobella**
Just add the `track_visibility='onchange'`

@lreficent @dalonsod @astirpe @jarroyomorales

### CODE REVIEW

**Review by jarroyomorales — APPROVED** [review]
It is interesting to track where an equipment used to belong, LGTM :+1:

**Review by dalonsod — COMMENTED** [review]
Tested 👍

**Review by dalonsod — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Comment by etobella** [comment]
@OCA/maintenance-maintainers  can you review please?

**Pull request merged**
