### PR TITLE
[16.0][MIG] maintenance_plan: Migration to 16.0

### PR DESCRIPTION
**Pull request by FernandoRomera**

### CODE REVIEW

**Comment by FernandoRomera** [comment]
#240

**Review by AntoniRomera — APPROVED** [review]

**Comment by victoralmau** [comment]
Please, cherry pick https://github.com/OCA/maintenance/pull/297 to commit history.

**Comment by victoralmau** [comment]
Please, cherry pick https://github.com/OCA/maintenance/pull/298 to commit history.

**Comment by victoralmau** [comment]
Please, cherry pick https://github.com/OCA/maintenance/pull/301 to commit history

**Comment by victoralmau** [comment]
Please, cherry pick https://github.com/OCA/maintenance/pull/305 to commit history

**Comment by victoralmau** [comment]
Please, cherry pick https://github.com/OCA/maintenance/pull/316 to commit history

**Comment by victoralmau** [comment]
Please, cherry pick https://github.com/OCA/maintenance/pull/319 to commit history

**Comment by FernandoRomera** [comment]
@victoralmau 
Do you know if the oca-port tool can be used to do this?

**Comment by victoralmau** [comment]
Please, cherry-pick https://github.com/OCA/maintenance/pull/332 to commit history

**Review by mamcode — APPROVED** [review]
Looks good for me, thanks

**Comment by etobella** [comment]
Can you cherry pick the commits?

**Comment by victoralmau** [comment]
Please, cherry-pick https://github.com/OCA/maintenance/pull/371 to commit history

**Comment by lk-eska** [comment]
I think this PR will never keep up with the 15.0 branch improvements.

**Comment by etobella** [comment]
Well, my feeling is that all the migrators of this module are not responding, I would recomend a new migration PR :sob:

**Comment by etobella** [comment]
Superseeded

**Pull request closed without merging**
