### PR TITLE
ci: run tests with GitHub actions

### PR DESCRIPTION
**Pull request by etobella**
Applies the same logic from https://github.com/OCA/mis-builder/pull/365
:crossed_fingers:

### CODE REVIEW

**Comment by etobella** [comment]
@JordiBForgeFlow I made a relicense on a module that you made. Can you check it?

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM, including the re-license of the ForgeFlow module :+1:

**Comment by etobella** [comment]
@sbidoul runbot is not launching. Something else is necessary or in this case there will be no more runbot?

**Comment by sbidoul** [comment]
@etobella you need to keep `.travis.yml` until runbot is updated.

**Comment by etobella** [comment]
But if the file exists, travis will be executed. Isn't it?

**Comment by sbidoul** [comment]
> But if the file exists, travis will be executed. Isn't it?

Yes, unfortunately...

**Comment by etobella** [comment]
Well runbot did not launch here also: https://github.com/OCA/maintenance/pull/155
Also, with the travis file restored (the first one prevents travis execution), it is not launched :sob: 
Any ideas @sbidoul ?

**Comment by sbidoul** [comment]
Maybe trying opening a new PR that does not remove .travis.yml ?

**Comment by etobella** [comment]
It has been restored and travis was executed

**Comment by etobella** [comment]
I will create a new PR. Let's see what happens ...

**Pull request closed without merging**
