### PR TITLE
[13.0][IMP] maintenance_plan: Add rules to maintenance.plan to view records of the equipments they follow

### PR DESCRIPTION
**Pull request by victoralmau**
Add rules to `maintenance.plan` to view records of the equipments they follow.

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT42535

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by dalonsod — APPROVED** [review]
👍

**Comment by dalonsod** [comment]
Pre-commit fails, doesn't it?

**Comment by pedrobaeza** [comment]
Pre-commit fixed in #327

/ocabot merge minor

**Comment by victoralmau** [comment]
Can you retry the process again?

**Pull request merged**
