### PR TITLE
[11.0][ADD] maintenance_remote

### PR DESCRIPTION
**Pull request by etobella**
This module allows to show the remote on a maintenance request where the issue
was created. It is useful on requests related to IT.

@jarroyomorales @JordiBForgeFlow

### CODE REVIEW

**Review by jarroyomorales — APPROVED** [review]
Simple but useful module. LGTM :+1:

**Review by dalonsod — APPROVED** [review]
👍 
Not blocking, maybe `remote_id` field should be only visible for a manager role, or when you are in debug mode.

**Comment by etobella** [comment]
Well, a usual user can only see his own issues, but we had the same thought and maybe we can create a specific group. I will check on a few days

**Comment by jarroyomorales** [comment]
Yes, now that you say it I also agree, even if users can only see their requests I think it is not necessary that they see information about their remote. This info is only useful to people that are going to work on the issue.

**Comment by etobella** [comment]
@jarroyomorales @dalonsod I made the changes you commented. I agree this is a better approach

**Comment by jarroyomorales** [comment]
@etobella Wouldnt it be easier to use the  `maintenance.group_equipment_manager` group instead of creating one just for this?

**Comment by etobella** [comment]
Well I decided to make a new group because people from a team may need the remote and other teams don't. But it is probably easier to use `maintenance.group_equipment_manager`

**Comment by jarroyomorales** [comment]
Nice then. Should this PR be merged? @etobella

**Comment by dalonsod** [comment]
I agree 👍

**Comment by etobella** [comment]
\ocabot merge

**Pull request merged**
