### PR TITLE
[15.0][MIG] maintenance_equipment_status

### PR DESCRIPTION
**Pull request by mariadforgeflow**
Standard migration to v15.

Depends on:

- [x] https://github.com/OCA/maintenance/pull/194

### CODE REVIEW

**Comment by etobella** [comment]
The same comment I made on #194 , Squash administrative commits please :wink:

**Review by OriolVForgeFlow — APPROVED** [review]
LGTM! Functional and code review.

**Review by BernatPForgeFlow — APPROVED** [review]

**Comment by mariadforgeflow** [comment]
@dreispt could you try to merge it again? I don't know why did it fail:/

**Comment by LoisRForgeFlow** [comment]
@etobella could you issue the merge again?

**Review by etobella — APPROVED** [review]

**Pull request merged**
