### PR TITLE
[12.0][MIG] maintenance_team_hierarchy

### PR DESCRIPTION
**Pull request by jarroyomorales**
Standard migration.
@etobella @dalonsod @NuriaMForgeFlow

### CODE REVIEW

**Comment by jarroyomorales** [comment]
Oops, its already here https://github.com/OCA/maintenance/pull/49 sorry.

**Comment by jarroyomorales** [comment]
Nevermind, everything is fine, mixed it with `maintenance_equipment_hierarchy` :rofl:

**Review by etobella — APPROVED** [review]
LGTM :+1: 
Simple migration.

**Comment by LoisRForgeFlow** [comment]
@NuriaMForgeFlow Could you review this?

**Review by NuriaXifre — APPROVED** [review]
Functional review done, LGTM

**Comment by etobella** [comment]
@jarroyomorales Could you join the translation commits in a single one and then we can proceed with the merge

**Pull request merged**
