### PR TITLE
[11.0][ADD] maintenance_plan_activity

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
This module allows defining in the maintenance plan activities that will be created once the maintenance
requests are created as a consequence of the plan itself.

cc ~ @Eficent

### CODE REVIEW

**Comment by astirpe** [comment]
@ageficent travis is red.
Can you also take a look at the [flake8 warnings](https://travis-ci.org/OCA/maintenance/jobs/563121265)?

**Comment by AdriaGForgeFlow** [comment]
> @ageficent travis is red.
> Can you also take a look at the [flake8 warnings](https://travis-ci.org/OCA/maintenance/jobs/563121265)?

I'm waiting for the improvement on maintenance_plan to be accepted and merged since this module depends on those improvements. Until then this PR is in stand by.

**Comment by etobella** [comment]
@ageficent maintenance plan has already been improved. Can you check?

**Comment by AdriaGForgeFlow** [comment]
> @ageficent maintenance plan has already been improved. Can you check?

Done :+1:

**Review by NuriaXifre — APPROVED** [review]
Functional review done! LGTM

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
