### PR TITLE
[12.0] Improve maintenance plan

### PR DESCRIPTION
**Pull request by etobella**
This PR includes the upgrades from
- [x] #19 
- [x] #59 
- [x] Fixes for the existing modules
I know this affects more than one module, but I don't want to have this failing.

@JordiBForgeFlow @LoisRForgeFlow @dalonsod @jarroyomorales

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks for forward porting that :+1:

**Review by AdriaGForgeFlow — APPROVED** [review]
Looking good! Thanks for the work :+1:

**Review by dalonsod — CHANGES_REQUESTED** [review]
Hello @etobella ,

thanks for `maintenance_project_plan` adaptations, I've tested them and look 👍 

Turning back to `maintenance_plan`,

- there are some travis warnings, could you take a look at them?
- I've found two issues, inherited from v11 implementation I think, maybe they'd be fixed in other PR, what do you think about it? (1) `maintenance.plan` form view display name seems to always show "False", and (2) when creating a plan from `maintenance.equipment` form, the equipment is not filled with the current one (that should also be set as `readonly`).

**Comment by etobella** [comment]
@dalonsod I fixed the travis issues.
About the issues, the problem is the following:
Name is not required, but it is used on the name, maybe we should need to define it as required. What do you think?
The other issue can be solved by setting a default.
I will make a PR on 11 solving this issues and we can cherry-pick the commit here. What do you think?

**Comment by etobella** [comment]
@dalonsod There was already a PR fixing it and it had been merged #56 I already included the commit :smile:

**Comment by etobella** [comment]
Some changes were necessary in order to make it work properly, something changed when computing the invisible on child elements.

@jarroyomorales

**Review by jarroyomorales — APPROVED** [review]
LGTM! :+1: Nice porting! But you should also have in mind to cherry pick #62

**Comment by dalonsod** [comment]
> Name is not required, but it is used on the name, maybe we should need to define it as required. What do you think?

I think a `name_get()` method should be enough for this issue, then preserving name field as not required. Anyway, this should be implemented in an independent PR, to be later cherry-picked to v11.

**Review by dalonsod — APPROVED** [review]
👍

**Pull request merged**
