### PR TITLE
[MIG] maintenance_request_repair: Migration to 15.0

### PR DESCRIPTION
**Pull request by kaynnan**

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @max3903

**Comment by marcelsavegnago** [comment]
ping @OCA/maintenance-maintainers

**Review by max3903 — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
@kaynnan Please migrate to version 16.0 as well.

**Pull request merged**
