### PR TITLE
[13.0][FIX]migration scripts not applicable in v13

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Moreover the version of the script is obsolete. In v12 was updated.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Yeah, that is also one of the reasons for removing always the scripts:

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
FYI this is `FIX`, not `DEL`. The correct tag `REM` is for removing an entire module.

**Comment by AaronHForgeFlow** [comment]
Sorry @pedrobaeza I force pushed the branch.

Could you try again?

**Comment by pedrobaeza** [comment]
No problem. It could be merged the other way (commit titles across OCA are worse than yours, I can assure you).

/ocabot merge nobump

**Pull request merged**
