### PR TITLE
[11.0][FIX] maintenance_equipment_tags: search view

### PR DESCRIPTION
**Pull request by jarroyomorales**
Adds search by tags to equipment.  Forgot to add in when creating the module and I think it is a mandatory feature.

@etobella @rousseldenis @ageficent

### CODE REVIEW

**Review by etobella — APPROVED** [review]
Now the module has more sense.
LGTM :+1:

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Review by astirpe — APPROVED** [review]
Tested in Runbot

**Pull request merged**
