### PR TITLE
 ci: run tests with GitHub actions 

### PR DESCRIPTION
**Pull request by etobella**
#154

### CODE REVIEW

**Comment by etobella** [comment]
Runbot is not being executed, but the .travis file has not been edited. Any idea? @sbidoul

**Comment by sbidoul** [comment]
No idea why runbot does not start here. Summoning @gurneyalex.

**Comment by MiquelRForgeFlow** [comment]
~~runbot is alive~~ :) runbo**a**t is alive

**Comment by etobella** [comment]
It works perfectly!!! :tada:

**Comment by sbidoul** [comment]
@etobella could-you do this one by running `copier update` and answering the question about CI or Travis ? So it will be persistent when we update the template.

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by etobella** [comment]
Ouch, It seems I need to make 2 PRs....

**Comment by sbidoul** [comment]
It's just that the bot does not have permissions to change GitHub workflows. But we can still merge manually :)

**Pull request merged**
