### PR TITLE
[16.0][IMP] maintenance_equipment_hierarchy - set unaccent to false on parent_path as proposed by warning logs

### PR DESCRIPTION
**Pull request by baimont**

### CODE REVIEW

**Review by dalonsod — APPROVED** [review]
👍

**Review by etobella — APPROVED** [review]

**Comment by dalonsod** [comment]
@baimont please prefix PR title with `[16.0]` if possible. Thanks for the contribution!

**Comment by etobella** [comment]
Can you check precommit?

**Comment by dalonsod** [comment]
@etobella pre-commit fails because a known gitlab access error. I've seen this problem in other repos, do you know how to solve it?

**Comment by etobella** [comment]
Yes, we need to do a copier update in order to fix it. On a separate PR

**Pull request merged**
