### PR TITLE
[17.0][MIG] maintenance_equipment_status: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 157017
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

- [Issue] https://github.com/OCA/field-service/issues/1132
Depends on:

- [base_maintenance] https://github.com/OCA/maintenance/pull/400

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
LGTM, checked in runboat

**Review by dalonsod — APPROVED** [review]
Code & functional review :+1: 

Only one thing, not blocking, is it possible to add status field management (search & group by) to equipments search view? It could be a nice and easy improvement IMO

**Review by lbarry-apsl — APPROVED** [review]
It works well. LGTM

**Comment by peluko00** [comment]
Seems is ready to merge @pedrobaeza ?

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration maintenance_equipment_status
/ocabot merge nobump

**Pull request merged**
