### PR TITLE
[13.0][FIX] maintenance_plan: fix new request date

### PR DESCRIPTION
**Pull request by albariera**
Cherry-pick from #203 
Thank you @mariadforgeflow! :blush:

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]
:)

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
This was actually implemented differently in v11 at the end https://github.com/OCA/maintenance/pull/202, version are not alligned now.

**Pull request merged**
