### PR TITLE
[14.0][FIX] maintenance_plan: fix new request date

### PR DESCRIPTION
**Pull request by mariadforgeflow**
When changing the start date of a plan (and setting it to a future one) new requests date weren't created as expected.

@ForgeFlow

### CODE REVIEW

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
@etobella How can we make this mergeable?

**Comment by LoisRForgeFlow** [comment]
Forward port of https://github.com/OCA/maintenance/pull/202

**Comment by LoisRForgeFlow** [comment]
Forward port of https://github.com/OCA/maintenance/pull/202.

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Can you update this to be aligned with the merged version at https://github.com/OCA/maintenance/pull/202.

**Comment by MiquelRForgeFlow** [comment]
> Can you update this to be aligned with the merged version at #202.

Better with https://github.com/OCA/maintenance/pull/204?

**Comment by LoisRForgeFlow** [comment]
> > Can you update this to be aligned with the merged version at #202.
> 
> Better with #204?

No, that one cherry-picked the v14 that is also incorrect, the initial change was reviewed and accepted in v11, and all the forward ports should have followed that one.

**Pull request merged**
