### PR TITLE
[16.0][MIG] maintenance_request_repair: Migration to 16.0

### PR DESCRIPTION
**Pull request by kaynnan**
cc @marcelsavegnago @augustodinizl 

#240

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Comment by marcelsavegnago** [comment]
ping @augustodinizl

**Comment by marcelsavegnago** [comment]
ping @augustodinizl

**Review by mamcode — APPROVED** [review]
LGTM, thanks

**Comment by etobella** [comment]
Can you squash all your migration commits on a single one?

**Comment by kaynnan** [comment]
> Can you squash all your migration commits on a single one?

Thanks for the comment, i squash it with the migration

**Pull request merged**
