### PR TITLE
[13.0][ADD] maintenance_request_stage_transition: add team_ids tags in stages

### PR DESCRIPTION
**Pull request by kluna1998**
With this change you are able to ocult some stages depending on the team.

### CODE REVIEW

**Review by etobella — APPROVED** [review]
Good addition. thanks

**Review by sanchonuria — APPROVED** [review]

**Comment by etobella** [comment]
@kluna1998 Can you rebase?

**Comment by kluna1998** [comment]
> @kluna1998 Can you rebase?

Done 😊

**Pull request merged**
