### PR TITLE
[14.0][MIG] maintenance_project

### PR DESCRIPTION
**Pull request by dalonsod**
Standard migration

### CODE REVIEW

**Comment by dalonsod** [comment]
cc @etobella @lmiguens-solvos

**Review by jarroyomorales — APPROVED** [review]
Tested on runbot and LGTM :+1:  There is an issue in project's form, but its not related to this module

**Review by lmiguens-solvos — APPROVED** [review]
LGTM

**Review by etobella — APPROVED** [review]

**Pull request merged**
