### PR TITLE
[FIX] maintenance_equipment_sequence write

### PR DESCRIPTION
**Pull request by etobella**
This was making to fail xmlrpc as he couldn't find the real answer.

@jarroyomorales @JordiBForgeFlow

### CODE REVIEW

**Review by jarroyomorales — APPROVED** [review]

**Comment by etobella** [comment]
@AdriaGForgeFlow @LoisRForgeFlow Can you review it please???

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Review by LoisRForgeFlow — APPROVED** [review]
this should be fast-tracked

**Pull request merged**
